baseURL = 'https://scholar7r.cn/'
languageCode = 'zh-CN'
title = 'Inkwell'
author = 'Scholar7r'
email = 'mail@scholar7r.cn'
disableHugoGeneratorInject = false

# Theme
theme = "nostyleplease"

favicon = "favicon.ico"

# Disable some kinds
disableKinds = ["taxonomy", "term"]

###
# Themes Configuration
###
[module]
[module.hugoVersion]
extended = true
min = "0.41.0"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
title = true

[markup.highlight]
style = 'github-dark'
tabWidth = 4

[params]
favicon = "favicon.ico"

[params.theme_config]
appearance = "auto"
back_home_text = ".."
date_format = "2006-01-02"
isListGroupByDate = true
isShowFooter = true
